# Setup
title:               Keelan Cook
tagline:             'North American Missiologist'
description:         'This is just an experiment with different ways of hosting my personal website. This  may grow into something more, but it will take some work for that to be the case.'
url:                 http://keelancook.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Keelan Cook
  url:               https://twitter.com/keelancook
  email:             keelan@ubahouston.org

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
