# Setup
title:               Keelan Cook
tagline:             'Missiologist'
description:         '<img src="/public/Cook Seal (1).png"> A test website for learning how to use Github Pages as an online home. This may grow into something more, but we will have to wait and see!'
url:                 https://keelancook.gq
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Keelan Cook
  url:               https://twitter.com/keelancook
  email:             keelan@ubahouston.org

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
